# Generated by Django 4.1.3 on 2023-06-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_on',
        ),
    ]
