# Generated by Django 4.1.3 on 2023-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_todo_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
