# Generated by Django 4.1.3 on 2023-06-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_todo_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_on',
            field=models.TimeField(blank=True),
        ),
    ]
